# Generated by Django 3.1.7 on 2021-03-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподователь', 'verbose_name_plural': 'Преподователи'},
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='s', max_length=150, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, upload_to='teachers/%Y/%m'),
        ),
    ]
